### ISSUE TITLE
Disconnect

### ISSUE THREAD

**Issue by fortunefavor** [Shinoyx/rk9guide#15]
When you disconnect in the middle of last boss and come back in again, the callouts become all messed up (wrong sequence, etc).

Also you might want to mention in the readme that you've changed the callouts to the actual safezones.

**Comment by Shinoyx** [comment]
@fortunefavor This is not a bug. Obviously when u dc the call outs would be wrong. The whole script gets re-initialized upon log in. Due to the fact that the script has no clue what the previous (or any mechs in-between). Most people that dc on last boss would probably restart the fight anyways.

Yes, I will update the readme with the callouts as well as new updates/functions that will be implemented real soon. 

Pm me on discord or open another ticket again if you face any issue or bug~
