### ISSUE TITLE
rk9guide bugged

### ISSUE THREAD

**Issue by vinny45** [Shinoyx/rk9guide#25]
Hi. Good morning.
well I have a problem with rk9guide in hard mode and extreme mode last boss.
when my party and me attack boss, this happen.
https://imgur.com/a/WiZ9m7f
https://imgur.com/a/Il5oHft
and too this.
https://imgur.com/a/9PapWIh
But when i am not in rk9hard or extreme. I'm fine in this happend and aanm too i am fine just have that problem in rk9 hard and extreme mode.
https://imgur.com/a/6zd0zZV
I'm using the last one proxy pinkie and node 10.5 and the last rk9guide but still so i have that bug and error on proxy.
Can you help me please :(
Thanks.

**Comment by Shinoyx** [comment]
I have users reporting to me about similar issues but that's caused by pinkie's proxy. I can't be bothered to fix it because most people uses caali proxy and this dungeon is quite old already.

For working version, try swapping over to Caali's proxy and if any of those issues still persist in caali proxy then I'll look into it.

**Comment by vinny45** [comment]
ok thanks :)
